# TCL File Generated by 
# Thu Nov 22 06:29:41 CET 2018
# DO NOT MODIFY


# 
# dupplReal_1_to_2 "dupplReal_1_to_2" v1.0
# ggm 2018.11.22.06:29:41
# dupplReal_1_to_2
# 

# 
# request TCL package from 
# 
package require -exact qsys 16.1


# 
# module dupplReal_1_to_2
# 
set_module_property DESCRIPTION dupplReal_1_to_2
set_module_property NAME dupplReal_1_to_2
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP cogen
set_module_property AUTHOR ggm
set_module_property DISPLAY_NAME dupplReal_1_to_2
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dupplReal_1_to_2
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dupplReal_1_to_2.vhd VHDL PATH hdl/dupplReal_1_to_2.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter DATA_SIZE NATURAL 8
set_parameter_property DATA_SIZE DEFAULT_VALUE 8
set_parameter_property DATA_SIZE DISPLAY_NAME DATA_SIZE
set_parameter_property DATA_SIZE TYPE NATURAL
set_parameter_property DATA_SIZE UNITS None
set_parameter_property DATA_SIZE ALLOWED_RANGES 0:2147483647
set_parameter_property DATA_SIZE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point data_in
# 
add_interface data_in conduit end
set_interface_property data_in associatedClock ""
set_interface_property data_in associatedReset ""
set_interface_property data_in ENABLED true
set_interface_property data_in EXPORT_OF ""
set_interface_property data_in PORT_NAME_MAP ""
set_interface_property data_in CMSIS_SVD_VARIABLES ""
set_interface_property data_in SVD_ADDRESS_GROUP ""

add_interface_port data_in data_en_i DATA_EN Input 1
add_interface_port data_in data_eof_i DATA_EOF Input 1
add_interface_port data_in data_clk_i DATA_CLK Input 1
add_interface_port data_in data_rst_i DATA_RST Input 1
add_interface_port data_in data_i DATA Input data_size


# 
# connection point data1_out
# 
add_interface data1_out conduit end
set_interface_property data1_out associatedClock ""
set_interface_property data1_out associatedReset ""
set_interface_property data1_out ENABLED true
set_interface_property data1_out EXPORT_OF ""
set_interface_property data1_out PORT_NAME_MAP ""
set_interface_property data1_out CMSIS_SVD_VARIABLES ""
set_interface_property data1_out SVD_ADDRESS_GROUP ""

add_interface_port data1_out data1_en_o DATA_EN Output 1
add_interface_port data1_out data1_eof_o DATA_EOF Output 1
add_interface_port data1_out data1_clk_o DATA_CLK Output 1
add_interface_port data1_out data1_rst_o DATA_RST Output 1
add_interface_port data1_out data1_o DATA Output data_size


# 
# connection point data2_out
# 
add_interface data2_out conduit end
set_interface_property data2_out associatedClock ""
set_interface_property data2_out associatedReset ""
set_interface_property data2_out ENABLED true
set_interface_property data2_out EXPORT_OF ""
set_interface_property data2_out PORT_NAME_MAP ""
set_interface_property data2_out CMSIS_SVD_VARIABLES ""
set_interface_property data2_out SVD_ADDRESS_GROUP ""

add_interface_port data2_out data2_en_o DATA_EN Output 1
add_interface_port data2_out data2_eof_o DATA_EOF Output 1
add_interface_port data2_out data2_clk_o DATA_CLK Output 1
add_interface_port data2_out data2_rst_o DATA_RST Output 1
add_interface_port data2_out data2_o DATA Output data_size


