set_property PACKAGE_PIN Y17 [get_ports {adc_data_a_i_0[0]}]
set_property PACKAGE_PIN W16 [get_ports {adc_data_a_i_0[1]}]
set_property PACKAGE_PIN Y16 [get_ports {adc_data_a_i_0[2]}]
set_property PACKAGE_PIN W15 [get_ports {adc_data_a_i_0[3]}]
set_property PACKAGE_PIN W14 [get_ports {adc_data_a_i_0[4]}]
set_property PACKAGE_PIN Y14 [get_ports {adc_data_a_i_0[5]}]
set_property PACKAGE_PIN W13 [get_ports {adc_data_a_i_0[6]}]
set_property PACKAGE_PIN V12 [get_ports {adc_data_a_i_0[7]}]
set_property PACKAGE_PIN V13 [get_ports {adc_data_a_i_0[8]}]
set_property PACKAGE_PIN T14 [get_ports {adc_data_a_i_0[9]}]
set_property PACKAGE_PIN T15 [get_ports {adc_data_a_i_0[10]}]
set_property PACKAGE_PIN V15 [get_ports {adc_data_a_i_0[11]}]
set_property PACKAGE_PIN T16 [get_ports {adc_data_a_i_0[12]}]
set_property PACKAGE_PIN V16 [get_ports {adc_data_a_i_0[13]}]
set_property PACKAGE_PIN R18 [get_ports {adc_data_b_i_0[0]}]
set_property PACKAGE_PIN P16 [get_ports {adc_data_b_i_0[1]}]
set_property PACKAGE_PIN P18 [get_ports {adc_data_b_i_0[2]}]
set_property PACKAGE_PIN N17 [get_ports {adc_data_b_i_0[3]}]
set_property PACKAGE_PIN R19 [get_ports {adc_data_b_i_0[4]}]
set_property PACKAGE_PIN T20 [get_ports {adc_data_b_i_0[5]}]
set_property PACKAGE_PIN T19 [get_ports {adc_data_b_i_0[6]}]
set_property PACKAGE_PIN U20 [get_ports {adc_data_b_i_0[7]}]
set_property PACKAGE_PIN V20 [get_ports {adc_data_b_i_0[8]}]
set_property PACKAGE_PIN W20 [get_ports {adc_data_b_i_0[9]}]
set_property PACKAGE_PIN W19 [get_ports {adc_data_b_i_0[10]}]
set_property PACKAGE_PIN Y19 [get_ports {adc_data_b_i_0[11]}]
set_property PACKAGE_PIN W18 [get_ports {adc_data_b_i_0[12]}]
set_property PACKAGE_PIN Y18 [get_ports {adc_data_b_i_0[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports adc_cdcs_0]
set_property PACKAGE_PIN V18 [get_ports adc_cdcs_0]
set_property PIO_DIRECTION OUTPUT [get_ports adc_cdcs_0]

set_property IOSTANDARD LVCMOS18 [get_ports {adc_data_a_i_0[*]}]
set_property IOB TRUE [get_ports {adc_data_a_i_0[*]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_data_b_i_0[*]}]
set_property IOB TRUE [get_ports {adc_data_b_i_0[*]}]



