#!/bin/sh
# Automatically generated by Amaranth 0.5.4. Do not edit.
set -e
if [ -z "$BASH" ] ; then exec /bin/bash "$0" "$@"; fi
[ -n "$AMARANTH_ENV_VIVADO" ] && . "$AMARANTH_ENV_VIVADO"
: ${VIVADO:=vivado}
"$VIVADO" -mode batch -log top.log -source top.tcl
