# Automatically generated by Amaranth 0.5.4. Do not edit.
set_property LOC U18 [get_ports "clk125_0__p"]
set_property IOSTANDARD "DIFF_HSTL_I_18" [get_ports "clk125_0__p"]
set_property LOC U19 [get_ports "clk125_0__n"]
set_property IOSTANDARD "DIFF_HSTL_I_18" [get_ports "clk125_0__n"]
create_clock -name clk125_0__p -period 8.0 [get_nets "clk125_0__p"]
# (add_constraints placeholder)