# TCL File Generated by Component Editor 18.0
# Thu Nov 22 06:41:16 CET 2018
# DO NOT MODIFY


# 
# prn20b "prn20b" v1.0
# ggm 2018.11.22.06:41:16
# prn20b
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module prn20b
# 
set_module_property DESCRIPTION prn20b
set_module_property NAME prn20b
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP cogen
set_module_property AUTHOR ggm
set_module_property DISPLAY_NAME prn20b
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL prn20b
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file prn20b.vhd VHDL PATH hdl/prn20b.vhd TOP_LEVEL_FILE
add_fileset_file prn20b_bitSync.vhd VHDL PATH hdl/prn20b_bitSync.vhd
add_fileset_file prn20b_handCom.vhd VHDL PATH hdl/prn20b_handCom.vhd
add_fileset_file prn20b_logic.vhd VHDL PATH hdl/prn20b_logic.vhd
add_fileset_file prn20b_presc.vhd VHDL PATH hdl/prn20b_presc.vhd
add_fileset_file prn20b_vectSync.vhd VHDL PATH hdl/prn20b_vectSync.vhd
add_fileset_file wb_prn20b.vhd VHDL PATH hdl/wb_prn20b.vhd


# 
# parameters
# 
add_parameter DFLT_PRESC NATURAL 15
set_parameter_property DFLT_PRESC DEFAULT_VALUE 15
set_parameter_property DFLT_PRESC DISPLAY_NAME DFLT_PRESC
set_parameter_property DFLT_PRESC TYPE NATURAL
set_parameter_property DFLT_PRESC UNITS None
set_parameter_property DFLT_PRESC ALLOWED_RANGES 0:2147483647
set_parameter_property DFLT_PRESC HDL_PARAMETER true
add_parameter PRESC_SIZE NATURAL 16
set_parameter_property PRESC_SIZE DEFAULT_VALUE 16
set_parameter_property PRESC_SIZE DISPLAY_NAME PRESC_SIZE
set_parameter_property PRESC_SIZE TYPE NATURAL
set_parameter_property PRESC_SIZE UNITS None
set_parameter_property PRESC_SIZE ALLOWED_RANGES 0:2147483647
set_parameter_property PRESC_SIZE HDL_PARAMETER true
add_parameter C_S00_AXI_DATA_WIDTH INTEGER 32 ""
set_parameter_property C_S00_AXI_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property C_S00_AXI_DATA_WIDTH DISPLAY_NAME C_S00_AXI_DATA_WIDTH
set_parameter_property C_S00_AXI_DATA_WIDTH WIDTH ""
set_parameter_property C_S00_AXI_DATA_WIDTH TYPE INTEGER
set_parameter_property C_S00_AXI_DATA_WIDTH UNITS None
set_parameter_property C_S00_AXI_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property C_S00_AXI_DATA_WIDTH DESCRIPTION ""
set_parameter_property C_S00_AXI_DATA_WIDTH HDL_PARAMETER true
add_parameter C_S00_AXI_ADDR_WIDTH INTEGER 3 ""
set_parameter_property C_S00_AXI_ADDR_WIDTH DEFAULT_VALUE 3
set_parameter_property C_S00_AXI_ADDR_WIDTH DISPLAY_NAME C_S00_AXI_ADDR_WIDTH
set_parameter_property C_S00_AXI_ADDR_WIDTH WIDTH ""
set_parameter_property C_S00_AXI_ADDR_WIDTH TYPE INTEGER
set_parameter_property C_S00_AXI_ADDR_WIDTH UNITS None
set_parameter_property C_S00_AXI_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property C_S00_AXI_ADDR_WIDTH DESCRIPTION ""
set_parameter_property C_S00_AXI_ADDR_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point s00_axi_aclk
# 
add_interface s00_axi_aclk clock end
set_interface_property s00_axi_aclk clockRate 0
set_interface_property s00_axi_aclk ENABLED true
set_interface_property s00_axi_aclk EXPORT_OF ""
set_interface_property s00_axi_aclk PORT_NAME_MAP ""
set_interface_property s00_axi_aclk CMSIS_SVD_VARIABLES ""
set_interface_property s00_axi_aclk SVD_ADDRESS_GROUP ""

add_interface_port s00_axi_aclk s00_axi_aclk clk Input 1


# 
# connection point s00_axi_reset
# 
add_interface s00_axi_reset reset end
set_interface_property s00_axi_reset associatedClock s00_axi_aclk
set_interface_property s00_axi_reset synchronousEdges DEASSERT
set_interface_property s00_axi_reset ENABLED true
set_interface_property s00_axi_reset EXPORT_OF ""
set_interface_property s00_axi_reset PORT_NAME_MAP ""
set_interface_property s00_axi_reset CMSIS_SVD_VARIABLES ""
set_interface_property s00_axi_reset SVD_ADDRESS_GROUP ""

add_interface_port s00_axi_reset s00_axi_reset reset Input 1


# 
# connection point s00_axi
# 
add_interface s00_axi axi4lite end
set_interface_property s00_axi associatedClock s00_axi_aclk
set_interface_property s00_axi associatedReset s00_axi_reset
set_interface_property s00_axi readAcceptanceCapability 1
set_interface_property s00_axi writeAcceptanceCapability 1
set_interface_property s00_axi combinedAcceptanceCapability 1
set_interface_property s00_axi readDataReorderingDepth 1
set_interface_property s00_axi bridgesToMaster ""
set_interface_property s00_axi ENABLED true
set_interface_property s00_axi EXPORT_OF ""
set_interface_property s00_axi PORT_NAME_MAP ""
set_interface_property s00_axi CMSIS_SVD_VARIABLES ""
set_interface_property s00_axi SVD_ADDRESS_GROUP ""

add_interface_port s00_axi s00_axi_awaddr awaddr Input c_s00_axi_addr_width
add_interface_port s00_axi s00_axi_awvalid awvalid Input 1
add_interface_port s00_axi s00_axi_awready awready Output 1
add_interface_port s00_axi s00_axi_wdata wdata Input c_s00_axi_data_width
add_interface_port s00_axi s00_axi_wvalid wvalid Input 1
add_interface_port s00_axi s00_axi_wready wready Output 1
add_interface_port s00_axi s00_axi_bresp bresp Output 2
add_interface_port s00_axi s00_axi_bvalid bvalid Output 1
add_interface_port s00_axi s00_axi_bready bready Input 1
add_interface_port s00_axi s00_axi_araddr araddr Input c_s00_axi_addr_width
add_interface_port s00_axi s00_axi_arvalid arvalid Input 1
add_interface_port s00_axi s00_axi_arready arready Output 1
add_interface_port s00_axi s00_axi_rdata rdata Output c_s00_axi_data_width
add_interface_port s00_axi s00_axi_rresp rresp Output 2
add_interface_port s00_axi s00_axi_rvalid rvalid Output 1
add_interface_port s00_axi s00_axi_rready rready Input 1
add_interface_port s00_axi s00_axi_arprot arprot Input 3
add_interface_port s00_axi s00_axi_awprot awprot Input 3
add_interface_port s00_axi s00_axi_wstrb wstrb Input c_s00_axi_data_width/8


# 
# connection point ref_clk_i
# 
add_interface ref_clk_i clock end
set_interface_property ref_clk_i clockRate 0
set_interface_property ref_clk_i ENABLED true
set_interface_property ref_clk_i EXPORT_OF ""
set_interface_property ref_clk_i PORT_NAME_MAP ""
set_interface_property ref_clk_i CMSIS_SVD_VARIABLES ""
set_interface_property ref_clk_i SVD_ADDRESS_GROUP ""

add_interface_port ref_clk_i ref_clk_i clk Input 1


# 
# connection point ref_rst_i
# 
add_interface ref_rst_i reset end
set_interface_property ref_rst_i associatedClock ref_clk_i
set_interface_property ref_rst_i synchronousEdges DEASSERT
set_interface_property ref_rst_i ENABLED true
set_interface_property ref_rst_i EXPORT_OF ""
set_interface_property ref_rst_i PORT_NAME_MAP ""
set_interface_property ref_rst_i CMSIS_SVD_VARIABLES ""
set_interface_property ref_rst_i SVD_ADDRESS_GROUP ""

add_interface_port ref_rst_i ref_rst_i reset Input 1


# 
# connection point prn_full_out
# 
add_interface prn_full_out conduit end
set_interface_property prn_full_out associatedClock ""
set_interface_property prn_full_out associatedReset ""
set_interface_property prn_full_out ENABLED true
set_interface_property prn_full_out EXPORT_OF ""
set_interface_property prn_full_out PORT_NAME_MAP ""
set_interface_property prn_full_out CMSIS_SVD_VARIABLES ""
set_interface_property prn_full_out SVD_ADDRESS_GROUP ""

add_interface_port prn_full_out prn_full_o DATA Output 20
add_interface_port prn_full_out prn_full_en_o DATA_EN Output 1
add_interface_port prn_full_out prn_full_clk_o DATA_CLK Output 1
add_interface_port prn_full_out prn_full_rst_o DATA_RST Output 1


# 
# connection point test_o
# 
add_interface test_o conduit end
set_interface_property test_o associatedClock ref_clk_i
set_interface_property test_o associatedReset ref_rst_i
set_interface_property test_o ENABLED true
set_interface_property test_o EXPORT_OF ""
set_interface_property test_o PORT_NAME_MAP ""
set_interface_property test_o CMSIS_SVD_VARIABLES ""
set_interface_property test_o SVD_ADDRESS_GROUP ""

add_interface_port test_o test_o test_o Output 1


# 
# connection point bit_o
# 
add_interface bit_o conduit end
set_interface_property bit_o associatedClock ref_clk_i
set_interface_property bit_o associatedReset ref_rst_i
set_interface_property bit_o ENABLED true
set_interface_property bit_o EXPORT_OF ""
set_interface_property bit_o PORT_NAME_MAP ""
set_interface_property bit_o CMSIS_SVD_VARIABLES ""
set_interface_property bit_o SVD_ADDRESS_GROUP ""

add_interface_port bit_o bit_o bit_o Output 1


