# TCL File Generated by Component Editor 18.0
# Thu Nov 01 08:52:29 CET 2018
# DO NOT MODIFY


# 
# pwm_axi "pwm_axi" v1.0
# Gwenhael Goavec-Merou <gwe@trabucayre.com> 2018.11.01.08:52:29
# pwm_axi
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pwm_axi
# 
set_module_property DESCRIPTION pwm_axi
set_module_property NAME pwm_axi
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP cogen
set_module_property AUTHOR "Gwenhael Goavec-Merou <gwe@trabucayre.com>"
set_module_property DISPLAY_NAME pwm_axi
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pwm_axi
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pwm_axi.vhd VHDL PATH hdl/pwm_axi.vhd TOP_LEVEL_FILE
add_fileset_file pwm_cpt.vhd VHDL PATH hdl/pwm_cpt.vhd
add_fileset_file pwm_handCom.vhd VHDL PATH hdl/pwm_handCom.vhd
add_fileset_file pwm_logic.vhd VHDL PATH hdl/pwm_logic.vhd
add_fileset_file pwm_comm.vhd VHDL PATH hdl/pwm_comm.vhd


# 
# parameters
# 
add_parameter ID NATURAL 0
set_parameter_property ID DEFAULT_VALUE 0
set_parameter_property ID DISPLAY_NAME ID
set_parameter_property ID TYPE NATURAL
set_parameter_property ID UNITS None
set_parameter_property ID ALLOWED_RANGES 0:2147483647
set_parameter_property ID HDL_PARAMETER true
add_parameter DATA_SIZE NATURAL 32
set_parameter_property DATA_SIZE DEFAULT_VALUE 32
set_parameter_property DATA_SIZE DISPLAY_NAME DATA_SIZE
set_parameter_property DATA_SIZE TYPE NATURAL
set_parameter_property DATA_SIZE UNITS None
set_parameter_property DATA_SIZE ALLOWED_RANGES 0:2147483647
set_parameter_property DATA_SIZE HDL_PARAMETER true
add_parameter cpt_overflow NATURAL 50
set_parameter_property cpt_overflow DEFAULT_VALUE 50
set_parameter_property cpt_overflow DISPLAY_NAME cpt_overflow
set_parameter_property cpt_overflow TYPE NATURAL
set_parameter_property cpt_overflow UNITS None
set_parameter_property cpt_overflow ALLOWED_RANGES 0:2147483647
set_parameter_property cpt_overflow HDL_PARAMETER true
add_parameter C_S00_AXI_DATA_WIDTH INTEGER 32
set_parameter_property C_S00_AXI_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property C_S00_AXI_DATA_WIDTH DISPLAY_NAME C_S00_AXI_DATA_WIDTH
set_parameter_property C_S00_AXI_DATA_WIDTH TYPE INTEGER
set_parameter_property C_S00_AXI_DATA_WIDTH UNITS None
set_parameter_property C_S00_AXI_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property C_S00_AXI_DATA_WIDTH HDL_PARAMETER true
add_parameter C_S00_AXI_ADDR_WIDTH INTEGER 5
set_parameter_property C_S00_AXI_ADDR_WIDTH DEFAULT_VALUE 5
set_parameter_property C_S00_AXI_ADDR_WIDTH DISPLAY_NAME C_S00_AXI_ADDR_WIDTH
set_parameter_property C_S00_AXI_ADDR_WIDTH TYPE INTEGER
set_parameter_property C_S00_AXI_ADDR_WIDTH UNITS None
set_parameter_property C_S00_AXI_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property C_S00_AXI_ADDR_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point s00_axi_aclk
# 
add_interface s00_axi_aclk clock end
set_interface_property s00_axi_aclk clockRate 0
set_interface_property s00_axi_aclk ENABLED true
set_interface_property s00_axi_aclk EXPORT_OF ""
set_interface_property s00_axi_aclk PORT_NAME_MAP ""
set_interface_property s00_axi_aclk CMSIS_SVD_VARIABLES ""
set_interface_property s00_axi_aclk SVD_ADDRESS_GROUP ""

add_interface_port s00_axi_aclk s00_axi_aclk clk Input 1


# 
# connection point s00_axi_reset
# 
add_interface s00_axi_reset reset end
set_interface_property s00_axi_reset associatedClock s00_axi_aclk
set_interface_property s00_axi_reset synchronousEdges DEASSERT
set_interface_property s00_axi_reset ENABLED true
set_interface_property s00_axi_reset EXPORT_OF ""
set_interface_property s00_axi_reset PORT_NAME_MAP ""
set_interface_property s00_axi_reset CMSIS_SVD_VARIABLES ""
set_interface_property s00_axi_reset SVD_ADDRESS_GROUP ""

add_interface_port s00_axi_reset s00_axi_reset reset Input 1


# 
# connection point pwm_o
# 
add_interface pwm_o conduit end
set_interface_property pwm_o associatedClock s00_axi_aclk
set_interface_property pwm_o associatedReset s00_axi_reset
set_interface_property pwm_o ENABLED true
set_interface_property pwm_o EXPORT_OF ""
set_interface_property pwm_o PORT_NAME_MAP ""
set_interface_property pwm_o CMSIS_SVD_VARIABLES ""
set_interface_property pwm_o SVD_ADDRESS_GROUP ""

add_interface_port pwm_o pwm_o export Output 1


# 
# connection point s00_axi
# 
add_interface s00_axi axi4lite end
set_interface_property s00_axi associatedClock s00_axi_aclk
set_interface_property s00_axi associatedReset s00_axi_reset
set_interface_property s00_axi readAcceptanceCapability 1
set_interface_property s00_axi writeAcceptanceCapability 1
set_interface_property s00_axi combinedAcceptanceCapability 1
set_interface_property s00_axi readDataReorderingDepth 1
set_interface_property s00_axi bridgesToMaster ""
set_interface_property s00_axi ENABLED true
set_interface_property s00_axi EXPORT_OF ""
set_interface_property s00_axi PORT_NAME_MAP ""
set_interface_property s00_axi CMSIS_SVD_VARIABLES ""
set_interface_property s00_axi SVD_ADDRESS_GROUP ""

add_interface_port s00_axi s00_axi_awaddr awaddr Input c_s00_axi_addr_width
add_interface_port s00_axi s00_axi_awprot awprot Input 3
add_interface_port s00_axi s00_axi_awvalid awvalid Input 1
add_interface_port s00_axi s00_axi_awready awready Output 1
add_interface_port s00_axi s00_axi_wdata wdata Input 32
add_interface_port s00_axi s00_axi_wstrb wstrb Input 4
add_interface_port s00_axi s00_axi_wvalid wvalid Input 1
add_interface_port s00_axi s00_axi_wready wready Output 1
add_interface_port s00_axi s00_axi_bresp bresp Output 2
add_interface_port s00_axi s00_axi_bvalid bvalid Output 1
add_interface_port s00_axi s00_axi_bready bready Input 1
add_interface_port s00_axi s00_axi_araddr araddr Input c_s00_axi_addr_width
add_interface_port s00_axi s00_axi_arprot arprot Input 3
add_interface_port s00_axi s00_axi_arvalid arvalid Input 1
add_interface_port s00_axi s00_axi_arready arready Output 1
add_interface_port s00_axi s00_axi_rdata rdata Output 32
add_interface_port s00_axi s00_axi_rresp rresp Output 2
add_interface_port s00_axi s00_axi_rvalid rvalid Output 1
add_interface_port s00_axi s00_axi_rready rready Input 1

