set_property IOSTANDARD DIFF_SSTL18_II [get_ports {phys_interface_0_adc_?_*}]
set_property IOB TRUE [get_ports {phys_interface_0_adc_?_*}]

set_property PACKAGE_PIN W18 [get_ports {phys_interface_0_adc_p_a[0]}]
set_property PACKAGE_PIN W19 [get_ports {phys_interface_0_adc_n_a[0]}]
set_property PACKAGE_PIN Y16 [get_ports {phys_interface_0_adc_p_a[1]}]
set_property PACKAGE_PIN Y17 [get_ports {phys_interface_0_adc_n_a[1]}]
set_property PACKAGE_PIN V12 [get_ports {phys_interface_0_adc_p_a[2]}]
set_property PACKAGE_PIN W13 [get_ports {phys_interface_0_adc_n_a[2]}]
set_property PACKAGE_PIN T11 [get_ports {phys_interface_0_adc_p_a[3]}]
set_property PACKAGE_PIN T10 [get_ports {phys_interface_0_adc_n_a[3]}]
set_property PACKAGE_PIN W14 [get_ports {phys_interface_0_adc_p_a[4]}]
set_property PACKAGE_PIN Y14 [get_ports {phys_interface_0_adc_n_a[4]}]
set_property PACKAGE_PIN V16 [get_ports {phys_interface_0_adc_p_a[5]}]
set_property PACKAGE_PIN W16 [get_ports {phys_interface_0_adc_n_a[5]}]
set_property PACKAGE_PIN T20 [get_ports {phys_interface_0_adc_p_a[6]}]
set_property PACKAGE_PIN U20 [get_ports {phys_interface_0_adc_n_a[6]}]

set_property PACKAGE_PIN N17 [get_ports {phys_interface_0_adc_p_b[0]}]
set_property PACKAGE_PIN P18 [get_ports {phys_interface_0_adc_n_b[0]}]
set_property PACKAGE_PIN T17 [get_ports {phys_interface_0_adc_p_b[1]}]
set_property PACKAGE_PIN R18 [get_ports {phys_interface_0_adc_n_b[1]}]
set_property PACKAGE_PIN T16 [get_ports {phys_interface_0_adc_p_b[2]}]
set_property PACKAGE_PIN U17 [get_ports {phys_interface_0_adc_n_b[2]}]
set_property PACKAGE_PIN V20 [get_ports {phys_interface_0_adc_p_b[3]}]
set_property PACKAGE_PIN W20 [get_ports {phys_interface_0_adc_n_b[3]}]
set_property PACKAGE_PIN Y18 [get_ports {phys_interface_0_adc_p_b[4]}]
set_property PACKAGE_PIN Y19 [get_ports {phys_interface_0_adc_n_b[4]}]
set_property PACKAGE_PIN T14 [get_ports {phys_interface_0_adc_p_b[5]}]
set_property PACKAGE_PIN T15 [get_ports {phys_interface_0_adc_n_b[5]}]
set_property PACKAGE_PIN V15 [get_ports {phys_interface_0_adc_p_b[6]}]
set_property PACKAGE_PIN W15 [get_ports {phys_interface_0_adc_n_b[6]}]


### ADC SPI control
set_property IOSTANDARD LVCMOS33 [get_ports phys_interface_0_adc_spi_*]
set_property SLEW SLOW [get_ports phys_interface_0_adc_spi_*]
set_property DRIVE 8 [get_ports phys_interface_0_adc_spi_*]
set_property PACKAGE_PIN U13 [get_ports phys_interface_0_adc_spi_csb]
set_property PACKAGE_PIN V18 [get_ports phys_interface_0_adc_spi_sdio]
set_property PACKAGE_PIN V13 [get_ports phys_interface_0_adc_spi_clk]
