# TCL File Generated by 
# Thu Nov 22 06:29:41 CET 2018
# DO NOT MODIFY


# 
# expanderReal "expanderReal" v1.0
# ggm 2018.11.22.06:29:41
# expanderReal
# 

# 
# request TCL package from 
# 
package require -exact qsys 16.1


# 
# module expanderReal
# 
set_module_property DESCRIPTION expanderReal
set_module_property NAME expanderReal
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP cogen
set_module_property AUTHOR ggm
set_module_property DISPLAY_NAME expanderReal
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL expanderReal
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file expanderReal.vhd VHDL PATH hdl/expanderReal.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter format STRING signed ""
set_parameter_property format DEFAULT_VALUE signed
set_parameter_property format DISPLAY_NAME format
set_parameter_property format WIDTH ""
set_parameter_property format TYPE STRING
set_parameter_property format UNITS None
set_parameter_property format DESCRIPTION ""
set_parameter_property format HDL_PARAMETER true
add_parameter DATA_IN_SIZE NATURAL 16
set_parameter_property DATA_IN_SIZE DEFAULT_VALUE 16
set_parameter_property DATA_IN_SIZE DISPLAY_NAME DATA_IN_SIZE
set_parameter_property DATA_IN_SIZE TYPE NATURAL
set_parameter_property DATA_IN_SIZE UNITS None
set_parameter_property DATA_IN_SIZE ALLOWED_RANGES 0:2147483647
set_parameter_property DATA_IN_SIZE HDL_PARAMETER true
add_parameter DATA_OUT_SIZE NATURAL 16
set_parameter_property DATA_OUT_SIZE DEFAULT_VALUE 16
set_parameter_property DATA_OUT_SIZE DISPLAY_NAME DATA_OUT_SIZE
set_parameter_property DATA_OUT_SIZE TYPE NATURAL
set_parameter_property DATA_OUT_SIZE UNITS None
set_parameter_property DATA_OUT_SIZE ALLOWED_RANGES 0:2147483647
set_parameter_property DATA_OUT_SIZE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point data_in
# 
add_interface data_in conduit end
set_interface_property data_in associatedClock ""
set_interface_property data_in associatedReset ""
set_interface_property data_in ENABLED true
set_interface_property data_in EXPORT_OF ""
set_interface_property data_in PORT_NAME_MAP ""
set_interface_property data_in CMSIS_SVD_VARIABLES ""
set_interface_property data_in SVD_ADDRESS_GROUP ""

add_interface_port data_in data_i DATA Input data_in_size
add_interface_port data_in data_en_i DATA_EN Input 1
add_interface_port data_in data_eof_i DATA_EOF Input 1
add_interface_port data_in data_rst_i DATA_RST Input 1
add_interface_port data_in data_clk_i DATA_CLK Input 1


# 
# connection point data_out
# 
add_interface data_out conduit end
set_interface_property data_out associatedClock ""
set_interface_property data_out associatedReset ""
set_interface_property data_out ENABLED true
set_interface_property data_out EXPORT_OF ""
set_interface_property data_out PORT_NAME_MAP ""
set_interface_property data_out CMSIS_SVD_VARIABLES ""
set_interface_property data_out SVD_ADDRESS_GROUP ""

add_interface_port data_out data_o DATA Output data_out_size
add_interface_port data_out data_en_o DATA_EN Output 1
add_interface_port data_out data_eof_o DATA_EOF Output 1
add_interface_port data_out data_rst_o DATA_RST Output 1
add_interface_port data_out data_clk_o DATA_CLK Output 1


