# TCL File Generated by 
# Thu Nov 22 06:29:41 CET 2018
# DO NOT MODIFY


# 
# axi_to_dac "axi_to_dac" v1.0
# ggm 2018.11.22.06:29:41
# axi_to_dac
# 

# 
# request TCL package from 
# 
package require -exact qsys 16.1


# 
# module axi_to_dac
# 
set_module_property DESCRIPTION axi_to_dac
set_module_property NAME axi_to_dac
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP cogen
set_module_property AUTHOR ggm
set_module_property DISPLAY_NAME axi_to_dac
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axi_to_dac
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file axi_to_dac.vhd VHDL PATH hdl/axi_to_dac.vhd TOP_LEVEL_FILE
add_fileset_file axi_to_dac_handcomm.vhd VHDL PATH hdl/axi_to_dac_handcomm.vhd
add_fileset_file wb_axi_to_dac.vhd VHDL PATH hdl/wb_axi_to_dac.vhd
add_fileset_file axi_to_dac_sync_vect.vhd VHDL PATH hdl/axi_to_dac_sync_vect.vhd


# 
# parameters
# 
add_parameter DATA_SIZE NATURAL 14
set_parameter_property DATA_SIZE DEFAULT_VALUE 14
set_parameter_property DATA_SIZE DISPLAY_NAME DATA_SIZE
set_parameter_property DATA_SIZE TYPE NATURAL
set_parameter_property DATA_SIZE UNITS None
set_parameter_property DATA_SIZE ALLOWED_RANGES 0:2147483647
set_parameter_property DATA_SIZE HDL_PARAMETER true
add_parameter DATAA_DEFAULT_OUT INTEGER 0 ""
set_parameter_property DATAA_DEFAULT_OUT DEFAULT_VALUE 0
set_parameter_property DATAA_DEFAULT_OUT DISPLAY_NAME DATAA_DEFAULT_OUT
set_parameter_property DATAA_DEFAULT_OUT WIDTH ""
set_parameter_property DATAA_DEFAULT_OUT TYPE INTEGER
set_parameter_property DATAA_DEFAULT_OUT UNITS None
set_parameter_property DATAA_DEFAULT_OUT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATAA_DEFAULT_OUT DESCRIPTION ""
set_parameter_property DATAA_DEFAULT_OUT HDL_PARAMETER true
add_parameter DATAB_DEFAULT_OUT INTEGER 0 ""
set_parameter_property DATAB_DEFAULT_OUT DEFAULT_VALUE 0
set_parameter_property DATAB_DEFAULT_OUT DISPLAY_NAME DATAB_DEFAULT_OUT
set_parameter_property DATAB_DEFAULT_OUT WIDTH ""
set_parameter_property DATAB_DEFAULT_OUT TYPE INTEGER
set_parameter_property DATAB_DEFAULT_OUT UNITS None
set_parameter_property DATAB_DEFAULT_OUT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATAB_DEFAULT_OUT DESCRIPTION ""
set_parameter_property DATAB_DEFAULT_OUT HDL_PARAMETER true
add_parameter DATAA_EN_ALWAYS_HIGH BOOLEAN false
set_parameter_property DATAA_EN_ALWAYS_HIGH DEFAULT_VALUE false
set_parameter_property DATAA_EN_ALWAYS_HIGH DISPLAY_NAME DATAA_EN_ALWAYS_HIGH
set_parameter_property DATAA_EN_ALWAYS_HIGH TYPE BOOLEAN
set_parameter_property DATAA_EN_ALWAYS_HIGH UNITS None
set_parameter_property DATAA_EN_ALWAYS_HIGH HDL_PARAMETER true
add_parameter DATAB_EN_ALWAYS_HIGH BOOLEAN false
set_parameter_property DATAB_EN_ALWAYS_HIGH DEFAULT_VALUE false
set_parameter_property DATAB_EN_ALWAYS_HIGH DISPLAY_NAME DATAB_EN_ALWAYS_HIGH
set_parameter_property DATAB_EN_ALWAYS_HIGH TYPE BOOLEAN
set_parameter_property DATAB_EN_ALWAYS_HIGH UNITS None
set_parameter_property DATAB_EN_ALWAYS_HIGH HDL_PARAMETER true
add_parameter id NATURAL 1
set_parameter_property id DEFAULT_VALUE 1
set_parameter_property id DISPLAY_NAME id
set_parameter_property id TYPE NATURAL
set_parameter_property id UNITS None
set_parameter_property id ALLOWED_RANGES 0:2147483647
set_parameter_property id HDL_PARAMETER true
add_parameter C_S00_AXI_DATA_WIDTH INTEGER 32 ""
set_parameter_property C_S00_AXI_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property C_S00_AXI_DATA_WIDTH DISPLAY_NAME C_S00_AXI_DATA_WIDTH
set_parameter_property C_S00_AXI_DATA_WIDTH WIDTH ""
set_parameter_property C_S00_AXI_DATA_WIDTH TYPE INTEGER
set_parameter_property C_S00_AXI_DATA_WIDTH UNITS None
set_parameter_property C_S00_AXI_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property C_S00_AXI_DATA_WIDTH DESCRIPTION ""
set_parameter_property C_S00_AXI_DATA_WIDTH HDL_PARAMETER true
add_parameter C_S00_AXI_ADDR_WIDTH INTEGER 4 ""
set_parameter_property C_S00_AXI_ADDR_WIDTH DEFAULT_VALUE 4
set_parameter_property C_S00_AXI_ADDR_WIDTH DISPLAY_NAME C_S00_AXI_ADDR_WIDTH
set_parameter_property C_S00_AXI_ADDR_WIDTH WIDTH ""
set_parameter_property C_S00_AXI_ADDR_WIDTH TYPE INTEGER
set_parameter_property C_S00_AXI_ADDR_WIDTH UNITS None
set_parameter_property C_S00_AXI_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property C_S00_AXI_ADDR_WIDTH DESCRIPTION ""
set_parameter_property C_S00_AXI_ADDR_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point ref_clk_i
# 
add_interface ref_clk_i clock end
set_interface_property ref_clk_i clockRate 0
set_interface_property ref_clk_i ENABLED true
set_interface_property ref_clk_i EXPORT_OF ""
set_interface_property ref_clk_i PORT_NAME_MAP ""
set_interface_property ref_clk_i CMSIS_SVD_VARIABLES ""
set_interface_property ref_clk_i SVD_ADDRESS_GROUP ""

add_interface_port ref_clk_i ref_clk_i clk Input 1


# 
# connection point ref_rst_i
# 
add_interface ref_rst_i reset end
set_interface_property ref_rst_i associatedClock ref_clk_i
set_interface_property ref_rst_i synchronousEdges DEASSERT
set_interface_property ref_rst_i ENABLED true
set_interface_property ref_rst_i EXPORT_OF ""
set_interface_property ref_rst_i PORT_NAME_MAP ""
set_interface_property ref_rst_i CMSIS_SVD_VARIABLES ""
set_interface_property ref_rst_i SVD_ADDRESS_GROUP ""

add_interface_port ref_rst_i ref_rst_i reset Input 1


# 
# connection point s00_axi_aclk
# 
add_interface s00_axi_aclk clock end
set_interface_property s00_axi_aclk clockRate 0
set_interface_property s00_axi_aclk ENABLED true
set_interface_property s00_axi_aclk EXPORT_OF ""
set_interface_property s00_axi_aclk PORT_NAME_MAP ""
set_interface_property s00_axi_aclk CMSIS_SVD_VARIABLES ""
set_interface_property s00_axi_aclk SVD_ADDRESS_GROUP ""

add_interface_port s00_axi_aclk s00_axi_aclk clk Input 1


# 
# connection point s00_axi_reset
# 
add_interface s00_axi_reset reset end
set_interface_property s00_axi_reset associatedClock s00_axi_aclk
set_interface_property s00_axi_reset synchronousEdges DEASSERT
set_interface_property s00_axi_reset ENABLED true
set_interface_property s00_axi_reset EXPORT_OF ""
set_interface_property s00_axi_reset PORT_NAME_MAP ""
set_interface_property s00_axi_reset CMSIS_SVD_VARIABLES ""
set_interface_property s00_axi_reset SVD_ADDRESS_GROUP ""

add_interface_port s00_axi_reset s00_axi_reset reset Input 1


# 
# connection point s00_axi
# 
add_interface s00_axi axi4lite end
set_interface_property s00_axi associatedClock s00_axi_aclk
set_interface_property s00_axi associatedReset s00_axi_reset
set_interface_property s00_axi readAcceptanceCapability 1
set_interface_property s00_axi writeAcceptanceCapability 1
set_interface_property s00_axi combinedAcceptanceCapability 1
set_interface_property s00_axi readDataReorderingDepth 1
set_interface_property s00_axi bridgesToMaster ""
set_interface_property s00_axi ENABLED true
set_interface_property s00_axi EXPORT_OF ""
set_interface_property s00_axi PORT_NAME_MAP ""
set_interface_property s00_axi CMSIS_SVD_VARIABLES ""
set_interface_property s00_axi SVD_ADDRESS_GROUP ""

add_interface_port s00_axi s00_axi_awaddr awaddr Input c_s00_axi_addr_width
add_interface_port s00_axi s00_axi_awvalid awvalid Input 1
add_interface_port s00_axi s00_axi_awready awready Output 1
add_interface_port s00_axi s00_axi_wdata wdata Input c_s00_axi_data_width
add_interface_port s00_axi s00_axi_wvalid wvalid Input 1
add_interface_port s00_axi s00_axi_wready wready Output 1
add_interface_port s00_axi s00_axi_bresp bresp Output 2
add_interface_port s00_axi s00_axi_bvalid bvalid Output 1
add_interface_port s00_axi s00_axi_bready bready Input 1
add_interface_port s00_axi s00_axi_araddr araddr Input c_s00_axi_addr_width
add_interface_port s00_axi s00_axi_arvalid arvalid Input 1
add_interface_port s00_axi s00_axi_arready arready Output 1
add_interface_port s00_axi s00_axi_rdata rdata Output c_s00_axi_data_width
add_interface_port s00_axi s00_axi_rresp rresp Output 2
add_interface_port s00_axi s00_axi_rvalid rvalid Output 1
add_interface_port s00_axi s00_axi_rready rready Input 1
add_interface_port s00_axi s00_axi_arprot arprot Input 3
add_interface_port s00_axi s00_axi_awprot awprot Input 3
add_interface_port s00_axi s00_axi_wstrb wstrb Input c_s00_axi_data_width/8


# 
# connection point dataA_out
# 
add_interface dataA_out conduit end
set_interface_property dataA_out associatedClock ""
set_interface_property dataA_out associatedReset ""
set_interface_property dataA_out ENABLED true
set_interface_property dataA_out EXPORT_OF ""
set_interface_property dataA_out PORT_NAME_MAP ""
set_interface_property dataA_out CMSIS_SVD_VARIABLES ""
set_interface_property dataA_out SVD_ADDRESS_GROUP ""

add_interface_port dataA_out dataA_o DATA Output data_size
add_interface_port dataA_out dataA_en_o DATA_EN Output 1
add_interface_port dataA_out dataA_eof_o DATA_EOF Output 1
add_interface_port dataA_out dataA_clk_o DATA_CLK Output 1
add_interface_port dataA_out dataA_rst_o DATA_RST Output 1


# 
# connection point dataB_out
# 
add_interface dataB_out conduit end
set_interface_property dataB_out associatedClock ref_clk_i
set_interface_property dataB_out associatedReset ref_rst_i
set_interface_property dataB_out ENABLED true
set_interface_property dataB_out EXPORT_OF ""
set_interface_property dataB_out PORT_NAME_MAP ""
set_interface_property dataB_out CMSIS_SVD_VARIABLES ""
set_interface_property dataB_out SVD_ADDRESS_GROUP ""

add_interface_port dataB_out dataB_o DATA Output data_size
add_interface_port dataB_out dataB_en_o DATA_EN Output 1
add_interface_port dataB_out dataB_eof_o DATA_EOF Output 1
add_interface_port dataB_out dataB_clk_o DATA_CLK Output 1
add_interface_port dataB_out dataB_rst_o DATA_RST Output 1

