# TCL File Generated by 
# Thu Nov 22 06:29:41 CET 2018
# DO NOT MODIFY


# 
# switchReal "switchReal" v1.0
# ggm 2018.11.22.06:29:41
# switchReal
# 

# 
# request TCL package from 
# 
package require -exact qsys 16.1


# 
# module switchReal
# 
set_module_property DESCRIPTION switchReal
set_module_property NAME switchReal
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP cogen
set_module_property AUTHOR ggm
set_module_property DISPLAY_NAME switchReal
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL switchReal
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file switchReal.vhd VHDL PATH hdl/switchReal.vhd TOP_LEVEL_FILE
add_fileset_file switchReal_handComm.vhd VHDL PATH hdl/switchReal_handComm.vhd
add_fileset_file switchReal_synch.vhd VHDL PATH hdl/switchReal_synch.vhd
add_fileset_file switchReal_wb.vhd VHDL PATH hdl/switchReal_wb.vhd


# 
# parameters
# 
add_parameter ID NATURAL 1
set_parameter_property ID DEFAULT_VALUE 1
set_parameter_property ID DISPLAY_NAME ID
set_parameter_property ID TYPE NATURAL
set_parameter_property ID UNITS None
set_parameter_property ID ALLOWED_RANGES 0:2147483647
set_parameter_property ID HDL_PARAMETER true
add_parameter DEFAULT_INPUT NATURAL 0
set_parameter_property DEFAULT_INPUT DEFAULT_VALUE 0
set_parameter_property DEFAULT_INPUT DISPLAY_NAME DEFAULT_INPUT
set_parameter_property DEFAULT_INPUT TYPE NATURAL
set_parameter_property DEFAULT_INPUT UNITS None
set_parameter_property DEFAULT_INPUT ALLOWED_RANGES 0:2147483647
set_parameter_property DEFAULT_INPUT HDL_PARAMETER true
add_parameter DATA_SIZE NATURAL 16
set_parameter_property DATA_SIZE DEFAULT_VALUE 16
set_parameter_property DATA_SIZE DISPLAY_NAME DATA_SIZE
set_parameter_property DATA_SIZE TYPE NATURAL
set_parameter_property DATA_SIZE UNITS None
set_parameter_property DATA_SIZE ALLOWED_RANGES 0:2147483647
set_parameter_property DATA_SIZE HDL_PARAMETER true
add_parameter C_S00_AXI_DATA_WIDTH INTEGER 32 ""
set_parameter_property C_S00_AXI_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property C_S00_AXI_DATA_WIDTH DISPLAY_NAME C_S00_AXI_DATA_WIDTH
set_parameter_property C_S00_AXI_DATA_WIDTH WIDTH ""
set_parameter_property C_S00_AXI_DATA_WIDTH TYPE INTEGER
set_parameter_property C_S00_AXI_DATA_WIDTH UNITS None
set_parameter_property C_S00_AXI_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property C_S00_AXI_DATA_WIDTH DESCRIPTION ""
set_parameter_property C_S00_AXI_DATA_WIDTH HDL_PARAMETER true
add_parameter C_S00_AXI_ADDR_WIDTH INTEGER 4 ""
set_parameter_property C_S00_AXI_ADDR_WIDTH DEFAULT_VALUE 4
set_parameter_property C_S00_AXI_ADDR_WIDTH DISPLAY_NAME C_S00_AXI_ADDR_WIDTH
set_parameter_property C_S00_AXI_ADDR_WIDTH WIDTH ""
set_parameter_property C_S00_AXI_ADDR_WIDTH TYPE INTEGER
set_parameter_property C_S00_AXI_ADDR_WIDTH UNITS None
set_parameter_property C_S00_AXI_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property C_S00_AXI_ADDR_WIDTH DESCRIPTION ""
set_parameter_property C_S00_AXI_ADDR_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point data1_in
# 
add_interface data1_in conduit end
set_interface_property data1_in associatedClock ""
set_interface_property data1_in associatedReset ""
set_interface_property data1_in ENABLED true
set_interface_property data1_in EXPORT_OF ""
set_interface_property data1_in PORT_NAME_MAP ""
set_interface_property data1_in CMSIS_SVD_VARIABLES ""
set_interface_property data1_in SVD_ADDRESS_GROUP ""

add_interface_port data1_in data1_i DATA Input data_size
add_interface_port data1_in data1_en_i DATA_EN Input 1
add_interface_port data1_in data1_clk_i DATA_CLK Input 1
add_interface_port data1_in data1_eof_i DATA_EOF Input 1
add_interface_port data1_in data1_rst_i DATA_RST Input 1


# 
# connection point data2_in
# 
add_interface data2_in conduit end
set_interface_property data2_in associatedClock ""
set_interface_property data2_in associatedReset ""
set_interface_property data2_in ENABLED true
set_interface_property data2_in EXPORT_OF ""
set_interface_property data2_in PORT_NAME_MAP ""
set_interface_property data2_in CMSIS_SVD_VARIABLES ""
set_interface_property data2_in SVD_ADDRESS_GROUP ""

add_interface_port data2_in data2_i DATA Input data_size
add_interface_port data2_in data2_en_i DATA_EN Input 1
add_interface_port data2_in data2_clk_i DATA_CLK Input 1
add_interface_port data2_in data2_eof_i DATA_EOF Input 1
add_interface_port data2_in data2_rst_i DATA_RST Input 1


# 
# connection point data_out
# 
add_interface data_out conduit end
set_interface_property data_out associatedClock ""
set_interface_property data_out associatedReset ""
set_interface_property data_out ENABLED true
set_interface_property data_out EXPORT_OF ""
set_interface_property data_out PORT_NAME_MAP ""
set_interface_property data_out CMSIS_SVD_VARIABLES ""
set_interface_property data_out SVD_ADDRESS_GROUP ""

add_interface_port data_out data_o DATA Output data_size
add_interface_port data_out data_en_o DATA_EN Output 1
add_interface_port data_out data_clk_o DATA_CLK Output 1
add_interface_port data_out data_eof_o DATA_EOF Output 1
add_interface_port data_out data_rst_o DATA_RST Output 1


# 
# connection point s00_axi_aclk
# 
add_interface s00_axi_aclk clock end
set_interface_property s00_axi_aclk clockRate 0
set_interface_property s00_axi_aclk ENABLED true
set_interface_property s00_axi_aclk EXPORT_OF ""
set_interface_property s00_axi_aclk PORT_NAME_MAP ""
set_interface_property s00_axi_aclk CMSIS_SVD_VARIABLES ""
set_interface_property s00_axi_aclk SVD_ADDRESS_GROUP ""

add_interface_port s00_axi_aclk s00_axi_aclk clk Input 1


# 
# connection point s00_axi_reset
# 
add_interface s00_axi_reset reset end
set_interface_property s00_axi_reset associatedClock s00_axi_aclk
set_interface_property s00_axi_reset synchronousEdges DEASSERT
set_interface_property s00_axi_reset ENABLED true
set_interface_property s00_axi_reset EXPORT_OF ""
set_interface_property s00_axi_reset PORT_NAME_MAP ""
set_interface_property s00_axi_reset CMSIS_SVD_VARIABLES ""
set_interface_property s00_axi_reset SVD_ADDRESS_GROUP ""

add_interface_port s00_axi_reset s00_axi_reset reset Input 1


# 
# connection point s00_axi
# 
add_interface s00_axi axi4lite end
set_interface_property s00_axi associatedClock s00_axi_aclk
set_interface_property s00_axi associatedReset s00_axi_reset
set_interface_property s00_axi readAcceptanceCapability 1
set_interface_property s00_axi writeAcceptanceCapability 1
set_interface_property s00_axi combinedAcceptanceCapability 1
set_interface_property s00_axi readDataReorderingDepth 1
set_interface_property s00_axi bridgesToMaster ""
set_interface_property s00_axi ENABLED true
set_interface_property s00_axi EXPORT_OF ""
set_interface_property s00_axi PORT_NAME_MAP ""
set_interface_property s00_axi CMSIS_SVD_VARIABLES ""
set_interface_property s00_axi SVD_ADDRESS_GROUP ""

add_interface_port s00_axi s00_axi_awaddr awaddr Input c_s00_axi_addr_width
add_interface_port s00_axi s00_axi_awvalid awvalid Input 1
add_interface_port s00_axi s00_axi_awready awready Output 1
add_interface_port s00_axi s00_axi_wdata wdata Input c_s00_axi_data_width
add_interface_port s00_axi s00_axi_wvalid wvalid Input 1
add_interface_port s00_axi s00_axi_wready wready Output 1
add_interface_port s00_axi s00_axi_bresp bresp Output 2
add_interface_port s00_axi s00_axi_bvalid bvalid Output 1
add_interface_port s00_axi s00_axi_bready bready Input 1
add_interface_port s00_axi s00_axi_araddr araddr Input c_s00_axi_addr_width
add_interface_port s00_axi s00_axi_arvalid arvalid Input 1
add_interface_port s00_axi s00_axi_arready arready Output 1
add_interface_port s00_axi s00_axi_rdata rdata Output c_s00_axi_data_width
add_interface_port s00_axi s00_axi_rresp rresp Output 2
add_interface_port s00_axi s00_axi_rvalid rvalid Output 1
add_interface_port s00_axi s00_axi_rready rready Input 1
add_interface_port s00_axi s00_axi_arprot arprot Input 3
add_interface_port s00_axi s00_axi_awprot awprot Input 3
add_interface_port s00_axi s00_axi_wstrb wstrb Input c_s00_axi_data_width/8


