set_property IOSTANDARD "LVCMOS33"	[get_ports "switch_o"]
set_property PACKAGE_PIN "Y11"	  	[get_ports "switch_o"]
set_property PIO_DIRECTION "OUTPUT"	[get_ports "switch_o"]
set_property IOSTANDARD "LVCMOS33"	[get_ports "switchn_o"]
set_property PACKAGE_PIN "AB11"	  	[get_ports "switchn_o"]
set_property PIO_DIRECTION "OUTPUT"	[get_ports "switchn_o"]
